# Generated by Django 5.0.3 on 2024-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sncfapp', '0002_alter_trains_destination_alter_trains_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='destination',
            field=models.CharField(max_length=40),
        ),
    ]
