# Generated by Django 5.0.3 on 2024-04-10 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sncfapp', '0006_alter_trains_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='arrive',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trains',
            name='departure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
